### PR TITLE
AWS task6

### PR DESCRIPTION
**Pull request by OlgaGnatenko**
**Main tasks**
1 (done) - File serverless.yml contains configuration for catalogBatchProcess function
2 (done) - File serverless.yml contains policies to allow lambda catalogBatchProcess function to interact with SNS and SQS
3 (done) - File serverless.yml contains configuration for SQS catalogItemsQueue
4 (done) - File serverless.yml contains configuration for SNS Topic createProductTopic and email subscription

No optional tasks for now, sorry :(

Links:
1. Backend endpoint: https://jh2vjbyda1.execute-api.eu-west-1.amazonaws.com/dev/products 
2. Import service: https://uyozw95jv6.execute-api.eu-west-1.amazonaws.com/dev/import
3. Frontend (add products interface): https://d2joi2c0vsqdd3.cloudfront.net/admin/products 

Note:
- SQS is added in import-service
- SNS is added in product-service 
- catalogBatchProcess  lambda is added in product-service

### CODE REVIEW

**Comment by MaksimPopov64** [comment]
It's not 6 task/ Where sqs or sns configuration/ Where lambdas for sqs?

**Comment by OlgaGnatenko** [comment]
@MaksimPopov64 I will push the solution today later, thank you! the deadline was extended, right?

**Comment by Savsan** [comment]
Hi! Where is a solution?

**Comment by OlgaGnatenko** [comment]
@Savsan, @MaksimPopov64 could you please take a look? I updated the solution. Will be very grateful if you have some time to check it. Thank you so much :)

**Pull request merged**
